import{ Imovie } from'./imovie'
export const dtMovies:Imovie[] =
   
   [{
        Id:1,
        Image: "\\assets\\Images\\image11.jpg",
        Name:"Padmawat",
        Star:5,
        Year:"2017",
        Genre:"Action",
        Actors:" Ranveer Singh,Deepika Padukone.",
        Director:"Sanjay Leela Bhansali",  
        ShortDescription:"Padmaavat released a month ago and stars Deepika Padukone with Ranveer Singh and Shahid Kapoor. The film has earned over 282 crore and the worldwide collection stands over Rs. 500 crore. The film based on Rani Padmavati, who had committed jauhar, after Alauddin Khilji invaded her fort. Ranveer plays Khilji in the film while Shahid stars as Maharawal Ratan Singh, Rani Padmavati's husband. "Padmaavat" is directed by Sanjay Leela Bhansali.",
    },
    {
        Id:2,
        Image: "\\assets\\Images\\newyork1.jpg",
        Name:"Welcome to New York",
        Star:3,
        Year:"2017",
        Genre:"Love",
        Actors:"Diljit Dosanjh, Sonakshi Sinha and Karan Johar",
        Director:"Chakri Toleti",
        ShortDescription:"Welcome to New York, starring Diljit Dosanjh, Sonakshi Sinha and Karan Johar, isn’t merely a bad film, or even a terrible one. It’s depressing. Not because the plot is all over the place (it is!), not because the actors appear to be doing whatever they like (they are!), and not because it has no vision or ambition (it doesn’t!) – but because it’s an exercise in sheer pointlessness. Really, this film has no reason to exist. ",
    },
    {
        Id:3,
        Image: "\\assets\\Images\\padman.jpg",
        Name:"Padman",
        Star:4.2,
        Year:"2017",
        Genre:"Action",
        Actors:"Akshay Kumar, Sonam Kapoor",
        Director:"R Balki",
        ShortDescription:"‘PadMan’ starring Akshay Kumar, Sonam Kapoor and Radhika Apte in lead roles, leaked onto social networking platform, Facebook. According to reports, the film that has been directed by R Balki, was uploaded online and allegedly shared over 5,000 times on the platform. This cybercrime was recorded just weeks after Sanjay Leela Bhansali’s magnum opus ‘Padmaavat’, starring Deepika Padukone, Ranveer Singh and Shahid Kapoor was streamed live on the platform.",
    },
    {
        Id:4,
        Image: "\\assets\\Images\\Image1.jpg",
        Name:"Padmawat",
        Star:5,
        Year:"2014",
        Genre:"Action",
        Actors:"ayz,abc",
        Director:"historical view ",
        ShortDescription:"",
    },
    {
        Id:5,
        Image: "\\assets\\Images\\Image1.jpg",
        Name:"RainBowt",
        Star:5,
        Year:"1995",
        Genre:"Love",
        Actors:"ayz,abc",
        Director:"historical view ",
        ShortDescription:"",
    },
    {
        Id:6,
        Image: "\\assets\\Images\\Image1.jpg",
        Name:"Padmawat",
        Star:5,
        Year:"2017",
        Genre:"Action",
        Actors:"ayz,abc",
        Director:"historical view ",
        ShortDescription:"",
    },
    {
        Id:7,
        Image: "\\assets\\Images\\Image1.jpg",
        Name:"Padmawat",
        Star:5,
        Year:"2014",
        Genre:"Action",
        Actors:"ayz,abc",
        Director:"historical view ",
        ShortDescription:"",
    }
    ];

   